name: Test GitHub Actions

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Hello
        run: echo "Hello from GitHub Actions 🚀"

      - name: Step 2 - Show Date
        run: date

      - name: Step 3 - Show Files
        run: ls -la
      - name: Step 4 - Fixing the error
        run: echo "This step is added to fix the error in the previous steps" 
      - name: Step 5 - debug infomation
        run: |
            echo "User : $(whoami)"
            echo "Current Directory : $(pwd)"
            echo "Environment Variables :"
            echo "Files:"
            ls -la
      - name: Step 6 - Build Step
        run: |
           mkdir build
           echo "Calculater App Ready for Build" > build/output.txt
           cat build/output.txt
      - name: Step 7 - Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
      - name: Step 8 - Show Uploaded Artifacts
        run: ls -la

      - name: Step 9 - Read Output File
        run: cat build/output.txt