name: Test GitHub Actions

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Hello
        run: echo "Hello from GitHub Actions 🚀"

      - name: Step 2 - Show Date
        run: date

      - name: Step 3 - Show Files
        run: ls -la
      - name: Step 4 - Fixing the error
        run: echo "This step is added to fix the error in the previous steps"

