name: Artifact Demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: |
          mkdir build
          echo "Calculator App Ready 🚀" > build/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Show Files
        run: ls -la

      - name: Read Output
        run: cat output.txt