name: Full CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: |
          mkdir build
          echo "Calculator App Ready 🚀" > build/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Run Test
        run: |
          if grep -q "Calculator" output.txt; then
            echo "Test Passed ✅"
          else
            echo "Test Failed ❌"
            exit 1
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Deploy Step
        run: echo "Deploying Calculator App 🚀"

      - name: Show Output
        run: cat output.txt